### ISSUE TITLE
problem emulating the app

### ISSUE THREAD

**Issue by tzookb** [ionic-in-action/ionic-demo-resort-app#1]
I already have several working projects with ionic,
but when I tried to build this app with the instructions I get this error:

```
 Error: ENOENT, no such file or directory '/Users/tzookb/Docs/ionic-demo-resort-app/plugins/ios.json'
```

any ideas why?

**Comment by gnomeontherun** [comment]
It seems to be an issue if there are no plugins. It still setup the files, but you might want to delete the platforms/ios directory and run the following. The first line will add the Ionic keyboard plugin and initialize the plugins directory, then you can add the ios platform without that error.

```
ionic plugin add com.ionic.keyboard
ionic platform add ios
```
