### ISSUE TITLE
Weather issue

### ISSUE THREAD

**Issue by ghost** [ionic-in-action/ionic-demo-resort-app#2]

**Comment by gnomeontherun** [comment]
It appears they are now enforcing a key like you say. 

You need to update the url in this line: https://github.com/ionic-in-action/ionic-demo-resort-app/blob/gh-pages/www/views/weather/weather.js#L7

```
$http.get('http://api.openweathermap.org/data/2.5/forecast/daily?q=Key%20West,FL&cnt=7&units=imperial&APPID=API_KEY_HERE').success(function (data) {
```

Replace `API_KEY_HERE` with your key to get authentication.

**Comment by AM981** [comment]
Thanks for the answer. I have already tried that but still doesnt work and cant find a solution.
My new line is 
$http.get('http://api.openweathermap.org/data/2.5/forecast/daily?q=Key%20West,FL&cnt=7&units=imperial&APPID=7892b533e0c0c0f197d6209c72aeae10').success(function (data) {
where my api key is 7892b533e0c0c0f197d6209c72aeae10.
And after building the program again, still getting the loading icon.

**Comment by gnomeontherun** [comment]
Did you also update the key here? 

https://github.com/ionic-in-action/ionic-demo-resort-app/blob/gh-pages/www/views/home/home.js#L41

**Comment by Tommy4444** [comment]
Thank you!
