### ISSUE TITLE
Events and food order

### ISSUE THREAD

**Issue by Tommy4444** [ionic-in-action/ionic-demo-resort-app#4]
Can you advice on how i can change the items in events? Can i modify the data.JSON file?
I don't know how the firebase thing works.

**Comment by gnomeontherun** [comment]
You can't modify the events in my database, you would have to setup your own database (which could be firebase or something else) and load data from there.

**Comment by Tommy4444** [comment]
Can you provide me the structure of the events page of your database?

**Comment by gnomeontherun** [comment]
You can inspect the request in the browser to view the data. It calls https://ionic-in-action-demo.firebaseio.com/events.json.
