### ISSUE TITLE
firebase question

### ISSUE THREAD

**Issue by Tommy4444** [ionic-in-action/ionic-demo-resort-app#5]
Hello, i have imported your JSON.data file in my firebase database in order to change some values but retain the whole structure. But when i'm changing the firebase link "var firebase = new Firebase('https://ionic-in-action-demo.firebaseio.com/menu');" with my projects link nohing happens.
Firebase had an update i think, can you assist me on how i can call the database with the new method? Thanks in advance.

**Comment by gnomeontherun** [comment]
I can't really troubleshoot this for you but you can use the fire base
support options to dig into what is going on.

On Saturday, June 4, 2016, Tommy4444 notifications@github.com wrote:

> Hello, i have imported your JSON.data file in my firebase database in
> order to change some values but retain the whole structure. But when i'm
> changing the firebase link "var firebase = new Firebase('
> https://ionic-in-action-demo.firebaseio.com/menu');" with my projects
> link nohing happens.
> Firebase had an update i think, can you assist me on how i can call the
> database with the new method? Thanks in advance.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/ionic-in-action/ionic-demo-resort-app/issues/5, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAE2jBBcpZDnsoDjf2-DwFNb0W3V8JS9ks5qIXvugaJpZM4IuIOv
> .

## 

---

Jeremy Wilken
