### ISSUE TITLE
About Firebase

### ISSUE THREAD

**Issue by AbcMausam** [ionic-in-action/ionic-demo-resort-app#6]
Hello...
My Question is that i have create my firebase console project.
can you please explain me that how to use that firebase console specification and it's data structure into this(https://github.com/ionic-in-action/ionic-demo-resort-app) demo project.?

**Comment by gnomeontherun** [comment]
You can get the raw data by looking for all of the Firebase URLs and adding `.json` to the end and requesting that payload.

Example: https://ionic-in-action-demo.firebaseio.com/events -> https://ionic-in-action-demo.firebaseio.com/events.json
